version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "yarn install && yarn dev"
    env_file:
      - .env
    networks:
      - public
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached
networks:
  public:
    driver: bridge
